
    create table district (
        district_id bigint not null,
        name varchar(255) not null,
        primary key (district_id)
    );

    create table population_stat_agg (
        period_start_date date not null,
        daytime_avg bigint,
        district_id bigint not null,
        nighttime_avg bigint,
        tot_avg bigint,
        period_type varchar(255) not null check (period_type in ('DAILY','WEEKLY','MONTHLY','YEARLY','DAYTIME','NIGHTTIME')),
        female_buckets_avg jsonb,
        male_buckets_avg jsonb,
        primary key (period_start_date, district_id, period_type)
    );

    create table population_stat_raw (
        stdr_de_id date not null,
        district_id bigint not null,
        tmzon_pd_se bigint not null,
        tot bigint,
        female_buckets jsonb,
        male_buckets jsonb,
        primary key (stdr_de_id, district_id, tmzon_pd_se)
    );

    create table user_account (
        created_at timestamp(6),
        user_id bigint generated by default as identity,
        email varchar(255) not null unique,
        password varchar(255) not null,
        role varchar(255) not null,
        primary key (user_id)
    );

    create table user_favorite_district (
        created_at timestamp(6),
        district_id bigint not null,
        user_id bigint not null,
        primary key (district_id, user_id)
    );

    create table user_note (
        created_at timestamp(6),
        district_id bigint,
        note_id bigint generated by default as identity,
        user_id bigint not null,
        content varchar(255),
        primary key (note_id)
    );

    create table user_preset (
        created_at timestamp(6),
        preset_id bigint generated by default as identity,
        user_id bigint not null,
        name varchar(255) not null,
        filters jsonb,
        primary key (preset_id)
    );

    alter table if exists population_stat_agg 
       add constraint FKishmibuo670ttkrfxruaf3w8r 
       foreign key (district_id) 
       references district;

    alter table if exists population_stat_raw 
       add constraint FK7sa1i0pmc5iue44vfp2q696we 
       foreign key (district_id) 
       references district;

    alter table if exists user_favorite_district 
       add constraint FKmisggolf5ftfeqchyqxn7d2am 
       foreign key (district_id) 
       references district;

    alter table if exists user_favorite_district 
       add constraint FK3ib068nawcqx9b6qlymqk6yvj 
       foreign key (user_id) 
       references user_account;

    alter table if exists user_note 
       add constraint FKar1v0dpis798uw4t2d8o5viur 
       foreign key (district_id) 
       references district;

    alter table if exists user_note 
       add constraint FKtpht7ct0jcgjvg643pfnafv5 
       foreign key (user_id) 
       references user_account;

    alter table if exists user_preset 
       add constraint FKl5hwm093hjyd0l4ow2b2uhin9 
       foreign key (user_id) 
       references user_account;
