server:
  port: 8080

spring:
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: kt
    password: kt123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate # 자동 변경 방지
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /docs

# CORS 설정 (WebConfig에서 주로 관리하지만 추가 설정 가능)
cors:
  allowed-origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
  max-age: 3600